### ISSUE TITLE
create a tool to easily build GHA

### ISSUE THREAD

**Issue by gmanchon** [lewagon/.github#5]
streamlit + form with bits and pieces of code

without history:
```
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
```

with full history:
```
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
```
